Repository q-unite/qunite-api, pull requests merged in 2023-08, with the labels that each got.

#111 Fix bug with changing member position
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
  src/test/java/com/qunite/api/service/QueueServiceTest.java
Labels: bug, refactor

#112 EntryUpdateDto fix validation
  src/main/java/com/qunite/api/web/dto/entry/EntryUpdateDto.java
Labels: bug

#107 Swagger docs extending
  src/main/java/com/qunite/api/QuniteApiApplication.java
  src/main/java/com/qunite/api/security/JwtAuthorizationFilter.java
  src/main/java/com/qunite/api/security/SecurityConfiguration.java
  src/main/java/com/qunite/api/web/controller/AuthenticationController.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/main/java/com/qunite/api/web/controller/UserController.java
Labels: documentation, enhancement

#113 Example values update due to DTO validation
  src/main/java/com/qunite/api/web/dto/queue/QueueUpdateDto.java
  src/main/java/com/qunite/api/web/dto/user/UserCreationDto.java
  src/main/java/com/qunite/api/web/dto/user/UserUpdateDto.java
Labels: documentation

#118 Add cross origin
  docker-compose.yml
  src/main/java/com/qunite/api/web/controller/AuthenticationController.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/main/java/com/qunite/api/web/controller/UserController.java
  src/test/resources/application-test.yml
Labels: enhancement

#114 Refactor enrolling member to queue
  src/main/java/com/qunite/api/service/QueueService.java
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/test/java/com/qunite/api/service/QueueServiceTest.java
  src/test/java/com/qunite/api/web/QueueControllerIntegrationTest.java
Labels: refactor
