Repository q-unite/qunite-api, pull requests merged in 2023-07, with the labels that each got.

#67 Security jwt filter implementation
  pom.xml
  src/main/java/com/qunite/api/data/UserRepository.java
  src/main/java/com/qunite/api/domain/User.java
  src/main/java/com/qunite/api/exception/QueueNotFoundException.java
  src/main/java/com/qunite/api/exception/UserAlreadyExistsException.java
  src/main/java/com/qunite/api/security/JwtAuthorizationFilter.java
  src/main/java/com/qunite/api/security/JwtService.java
  src/main/java/com/qunite/api/security/SecurityConfiguration.java
  src/main/java/com/qunite/api/security/UserDetailsServiceImpl.java
  src/main/java/com/qunite/api/service/QueueService.java
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
  src/main/java/com/qunite/api/service/UserService.java
  src/main/java/com/qunite/api/service/UserServiceImpl.java
  src/main/java/com/qunite/api/web/ResponseEntityControllerAdvice.java
  src/main/java/com/qunite/api/web/controller/AuthenticationController.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/main/java/com/qunite/api/web/controller/UserController.java
  src/main/java/com/qunite/api/web/dto/ExceptionResponse.java
  src/main/java/com/qunite/api/web/dto/auth/AuthenticationRequest.java
  src/main/java/com/qunite/api/web/dto/auth/AuthenticationResponse.java
  src/main/java/com/qunite/api/web/dto/user/UserCreationDto.java
  src/main/java/com/qunite/api/web/dto/user/UserDto.java
  src/main/java/com/qunite/api/web/dto/user/UserUpdateDto.java
  src/main/java/com/qunite/api/web/mapper/AuthResponseMapper.java
  src/test/java/com/qunite/api/service/QueueServiceTest.java
  src/test/java/com/qunite/api/service/UserServiceTest.java
  src/test/java/com/qunite/api/web/QueueControllerTest.java
  src/test/java/com/qunite/api/web/UserControllerTest.java
  src/test/resources/application-test.yml
  src/test/resources/db/migration/V1_0_0__init_schema.sql
  src/test/resources/users-create.sql
Labels: enhancement

#86 fixed Swagger 403 response bug
  src/main/java/com/qunite/api/security/SecurityConfiguration.java
Labels: bug

#80 Add queue manipulating endpoints
  pom.xml
  src/main/java/com/qunite/api/data/EntryRepository.java
  src/main/java/com/qunite/api/data/UserRepository.java
  src/main/java/com/qunite/api/exception/EntryNotFoundException.java
  src/main/java/com/qunite/api/exception/ForbiddenAccessException.java
  src/main/java/com/qunite/api/security/UserDetailsServiceImpl.java
  src/main/java/com/qunite/api/service/QueueService.java
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
  src/main/java/com/qunite/api/service/UserServiceImpl.java
  src/main/java/com/qunite/api/web/ResponseEntityControllerAdvice.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/main/java/com/qunite/api/web/dto/entry/EntryUpdateDto.java
  src/main/java/com/qunite/api/web/mapper/EntryMapper.java
  src/test/java/com/qunite/api/data/EntityLifecycleTest.java
  src/test/java/com/qunite/api/service/QueueServiceTest.java
  src/test/java/com/qunite/api/web/QueueControllerTest.java
Labels: enhancement

#93 Refactor controller advice
  src/main/java/com/qunite/api/web/ResponseEntityControllerAdvice.java
Labels: refactor

#101 Swap checks for forbidden and not found
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
Labels: refactor

#102 Sign-in method refactor
  src/main/java/com/qunite/api/exception/InvalidPasswordException.java
  src/main/java/com/qunite/api/service/UserServiceImpl.java
  src/main/java/com/qunite/api/web/ResponseEntityControllerAdvice.java
  src/test/java/com/qunite/api/web/AuthenticationIntegrationTest.java
Labels: refactor

#103 Endpoints for manipulating with queue's managers
  src/main/java/com/qunite/api/data/QueueRepository.java
  src/main/java/com/qunite/api/service/QueueService.java
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/main/java/com/qunite/api/web/controller/UserController.java
  src/test/java/com/qunite/api/service/QueueServiceTest.java
  src/test/java/com/qunite/api/web/QueueControllerIntegrationTest.java
Labels: bug, enhancement

#106 Kebab case refactor
  src/main/java/com/qunite/api/web/controller/QueueController.java
Labels: refactor

#108 Add leave from queue endpoint
  src/main/java/com/qunite/api/service/QueueService.java
  src/main/java/com/qunite/api/service/QueueServiceImpl.java
  src/main/java/com/qunite/api/web/ResponseEntityControllerAdvice.java
  src/main/java/com/qunite/api/web/controller/QueueController.java
  src/test/java/com/qunite/api/service/QueueServiceTest.java
Labels: enhancement
